name: aural_sight
description: "Let Your Ears Guide Your Eyes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  camera: ^0.12.0+1
  flutter_tts: ^4.2.5
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  
  # Voice Assistant (audio capture)
  record: 6.2.0
  permission_handler: 11.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.1.0
  vosk_flutter: ^0.3.0

  # Local database
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Object Detection
  tflite_flutter: ^0.12.1
  image: ^4.8.0

  # OCR with ML Kit (offline)
  google_mlkit_text_recognition: ^0.15.1

  # Icons
  cupertino_icons: ^1.0.9

  hand_detection: ^3.0.6
  sensors_plus: ^6.1.2   # latest


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: 0.14.4

dependency_overrides:
  archive: 4.0.0
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  permission_handler_apple: ^9.4.5
  permission_handler_platform_interface: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/teammgh.png
    - assets/model/ssd_mobilenet_v1.tflite
    - assets/model/hand_landmark.tflite
    - assets/model/vosk-model-small-en-us-0.15.zip
    - assets/label/labels.txt
    - assets/images/mapplogo4.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mapplogo4.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/mapplogo4.png"
 